import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { completeWorkout, getTrainDashboard, logWorkoutSet, skipWorkoutSet, startWorkout, type TrainDashboard } from '../../../application/services/workoutService';

export function TrainScreen(){
  const[state,setState]=useState<TrainDashboard|null>(null);const[status,setStatus]=useState('');
  async function refresh(){setState(await getTrainDashboard());}
  useEffect(()=>{void getTrainDashboard().then(setState);},[]);
  async function begin(){if(!state?.dayId)return;try{await startWorkout(state.dayId);setStatus('Workout started.');await refresh();}catch(error){setStatus(error instanceof Error?error.message:'Unable to start workout.');}}
  async function logSet(event:FormEvent<HTMLFormElement>,exerciseId:string,setOrdinal:number){event.preventDefault();if(!state?.activeWorkout)return;const formElement=event.currentTarget;const form=new FormData(formElement);const weight=Number(form.get('weight'));const reps=Number(form.get('reps'));try{await logWorkoutSet(state.activeWorkout.id,exerciseId,setOrdinal,weight,reps);formElement.reset();setStatus('Set logged.');await refresh();}catch(error){setStatus(error instanceof Error?error.message:'Unable to log set.');}}
  async function skip(exerciseId:string,setOrdinal:number){if(!state?.activeWorkout)return;try{await skipWorkoutSet(state.activeWorkout.id,exerciseId,setOrdinal);setStatus('Set skipped.');await refresh();}catch(error){setStatus(error instanceof Error?error.message:'Unable to skip set.');}}
  async function finish(){if(!state?.activeWorkout)return;try{const closed=await completeWorkout(state.activeWorkout.id);setStatus(`Workout ${closed.status.toLowerCase()}.`);await refresh();}catch(error){setStatus(error instanceof Error?error.message:'Unable to complete workout.');}}
  if(!state)return <section><div className="eyebrow">TRAIN</div><h1>Loading…</h1></section>;
  const activeTemplate=state.activeTemplate;
  return <section><div className="eyebrow">TRAIN</div><h1>{state.activeWorkout&&activeTemplate?`Workout ${activeTemplate.id} · ${activeTemplate.emphasis}`:`Next: Workout ${state.nextTemplate.id} · ${state.nextTemplate.emphasis}`}</h1>{status&&<p role="status" className="card">{status}</p>}
    {!state.dayId?<div className="card"><h2>No active day</h2><p className="muted">Start a BEYOND Day before training.</p><Link to="/today">GO TO TODAY</Link></div>:state.activeWorkout&&activeTemplate?<>
      {activeTemplate.exercises.map((exercise)=>{const guidance=state.guidance.find((item)=>item.exerciseId===exercise.id);return <div className="card" key={exercise.id}><h2>{exercise.name}</h2><p>{exercise.setCount} sets · {exercise.repMin}–{exercise.repMax} reps</p>{guidance&&<p className="muted">Previous: {guidance.previous.length?guidance.previous.map((set)=>set.state==='COMPLETED'?`${set.weight}×${set.reps}`:'SKIP').join(' / '):'NONE'} · Next: {guidance.progression.action}</p>}
        {Array.from({length:exercise.setCount},(_,index)=>index+1).map((ordinal)=>{const recorded=state.activeSets.find((set)=>set.exerciseId===exercise.id&&set.setOrdinal===ordinal);return <div key={ordinal}>{recorded?<p><strong>Set {ordinal}:</strong> {recorded.state==='COMPLETED'?`${recorded.weight} × ${recorded.reps}`:'SKIPPED'}</p>:<form onSubmit={(event)=>logSet(event,exercise.id,ordinal)}><strong>Set {ordinal}</strong><label>{exercise.name} set {ordinal} weight<input name="weight" type="number" min="0" step="0.5" required/></label><label>{exercise.name} set {ordinal} reps<input name="reps" type="number" min="1" step="1" required/></label><p><button type="submit">LOG SET</button> <button type="button" onClick={()=>skip(exercise.id,ordinal)}>SKIP</button></p></form>}</div>;})}</div>;})}
      <p><button onClick={finish}>COMPLETE SESSION</button></p></>:<><div className="card"><h2>Workout {state.nextTemplate.id}</h2>{state.nextTemplate.exercises.map((exercise)=>{const guidance=state.guidance.find((item)=>item.exerciseId===exercise.id);return <p key={exercise.id}><strong>{exercise.name}</strong> · {exercise.setCount}×{exercise.repMin}–{exercise.repMax}{guidance?<><br/><span className="muted">{guidance.progression.action}: {guidance.progression.reason}</span></>:null}</p>;})}<button onClick={begin}>START WORKOUT</button></div>{state.history.length>0&&<div className="card"><h2>Recent sessions</h2>{state.history.map((session)=><p key={session.id}>Workout {session.templateId??'—'} · {session.sessionType} · {session.status}</p>)}</div>}</>}
  </section>;
}
